import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles/Home.module.css";

// const defaultEndpoint = `https://api.unsplash.com/photos/?client_id=8hic3xQLEc5anDmp61ZPRuYDt85tvvKxJeXRdqEEIiY
// `;

export async function getServerSideProps({query}) {
  
  const { id } = query;
  const res = await fetch(`https://api.unsplash.com/photos/${id}/?client_id=8hic3xQLEc5anDmp61ZPRuYDt85tvvKxJeXRdqEEIiY`);
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
export default function Detail({ data }) {
  console.log("data", data);

  const { id, urls, user } = data;
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <img src={urls.regular} className={styles.detail_image} />

      <h1 className={styles.title}>Id: {id}</h1>
      <h1 className={styles.title}>User: {user.username}</h1>

      </main>

    </div>
  );
}
